//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace List.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tarefas
    {
        public int id { get; set; }
        public string ds_titulo { get; set; }
        public bool fg_finalizado { get; set; }
        public string ds_descricao { get; set; }
        public Nullable<System.DateTime> dt_criado { get; set; }
        public Nullable<System.DateTime> dt_editado { get; set; }
        public Nullable<System.DateTime> dt_deletado { get; set; }
        public Nullable<System.DateTime> dt_concluido { get; set; }
    }
}
